const Menu=[{
    id:1,
    image:"pic/waff.jpg",
    name:"Waffles",
    category :"Breakfast",
    price:125,
    description:"fine..",
},
{
    id: 2,
    image: "pic/aloo.jpg",
    name: "alloo parotha",
    category: "Evening",
    price: "35₹",
    description:"Amazing..",
  },
  {
    id: 3,
    image: "pic/puff.jpg",
    name: "puff",
    category: "Breakfast",
    price: "23₹",
    description:"Tasty...",
  },
  {
    id: 4,
    image: "pic/chole.jpg",
    name: "chole-bhature",
    category: "lunch",
    price: "60₹",
    description:"Awesome...",
  },
  {
    id: 5,
    image: "pic/pizza.jpg",
    name: "pizza",
    category: "Evening",
    price: "125₹",
    description:"yummy..",
  },
  {
    id: 6,
    image: "pic/guj.jpg",
    name: "Gujarati Thali",
    category: "Dinner",
    price: "90₹",
    description:
      "simple ans sweet..",
  },
  {
    id: 7,
    image: "pic/des.jpg",
    name: "desert",
    category: "Dinner",
    price: "60₹",
    description:"cool...",
  },
  {
    id: 8,
    image: "pic/dalbati.jpg",
    name: "Dal bati",
    category: "lunch",
    price: "90₹",
    description:"superb....",
  },
  {
    id: 9,
    image: "pic/dhosa.jpg",
    name: "dhosa",
    category: "Evening",
    price: "50₹",
    description:"nice..",
  },
];
export default Menu;